name: cold-start-forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0
  - bokeh=3.2.2
  - jupyter=1.0.0
  - ipykernel=6.27.1
  - pip:
    - prophet==1.1.4
    - statsmodels==0.14.0
    - lightgbm==4.0.0
    - xgboost==1.7.6
    - catboost==1.2.2
    - torch==2.0.1
    - tensorflow==2.13.0
    - keras==2.13.1
    - shap==0.42.1
    - lime==0.2.0.1
    - eli5==0.13.0
    - tqdm==4.65.0
    - joblib==1.3.2
    - pyyaml==6.0.1
    - python-dotenv==1.0.0
    - pytest==7.4.0
    - black==23.7.0
    - flake8==6.0.0
    - openpyxl==3.1.2
    - xlsxwriter==3.1.2
